<%@ Page Title="套餐維護" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="PkgAddEdit.aspx.cs" Inherits="HMCSys.PkgAddEdit" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <div class="row">
		<div class="col-sm-12">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h3 class="panel-title">
                        <asp:Label ID="Label1" runat="server" Text=""></asp:Label>套餐</h3>
				</div>
				<div class="panel-body">
					<div class="form-group text-center">
						<span style="color: #FF5050">
							<%=PublicLib.Notice %></span>
					</div>
					<div class="form-group">
						<span class="col-sm-2 control-label" style="color: #FF5050">*名稱</span>
						<div class="col-sm-10">
							<asp:TextBox ID="txtName" runat="server" CssClass="form-control"></asp:TextBox>
						</div>
					</div>
					<div class="form-group">
						<span class="col-sm-2 control-label" style="color: #FF5050">*套餐代碼</span>
						<div class="col-sm-4">
							<asp:TextBox ID="txtPkgCode" runat="server" CssClass="form-control" style="TEXT-TRANSFORM:   uppercase"></asp:TextBox>
                            <asp:Label ID="lbCheckCode" runat="server" ForeColor="Red"></asp:Label>
						</div>
                        <span class="col-sm-2 control-label" style="color: #FF5050">*套餐金額</span>
						<div class="col-sm-4">
							<asp:TextBox ID="txtPkgPrice" runat="server" CssClass="form-control" onkeypress="return number_only(event)"></asp:TextBox>
                            <%--<asp:RegularExpressionValidator ID="RegularExpressionValidator1" ControlToValidate="txtPrice" runat="server" ErrorMessage="請輸入數字" ValidationExpression="\d+" Font-Overline="False" ForeColor="Red"></asp:RegularExpressionValidator>--%>
						</div>
					</div>
                    <div class="form-group">
                        <span class="col-sm-2 control-label" style="color: #FF5050">*套餐細項</span>
                        <div class="col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon">細項代碼</span>
                                <asp:TextBox ID="txtItemCode" runat="server" CssClass="form-control"></asp:TextBox>
                                <asp:TextBox ID="txtItemName" runat="server" CssClass="form-control" Enabled="False" Visible="False"></asp:TextBox>
                                <asp:TextBox ID="txtItemPrice" runat="server" CssClass="form-control" Enabled="False" Visible="False"></asp:TextBox>
                                <span class="input-group-btn">
                                    <asp:Button ID="btnAdd" runat="server" Text="新增細項" CssClass="btn btn-success" OnClick="btnAdd_Click" />
                                </span>
                            </div>
                            <hr />
                            <div class="table-responsive">
                                <asp:GridView ID="GridView1" runat="server" CssClass="table table-bordered" DataKeyNames="ItemCode" AutoGenerateColumns="false" AutoGenerateDeleteButton="False">
                                    <Columns>
                                        <asp:BoundField HeaderText="細項代碼" DataField="ItemCode" />
                                        <asp:BoundField HeaderText="細項名稱" DataField="ItemName" />
                                        <asp:BoundField HeaderText="細項金額" DataField="ItemPrice" />
                                        <asp:TemplateField HeaderText="刪除">
                                            <ItemTemplate>
                                                <asp:CheckBox ID="Ckb_Del" runat="server" />
                                            </ItemTemplate>
                                            <ItemStyle Width="60px" HorizontalAlign="Center" />
                                        </asp:TemplateField>
                                    </Columns>
                                    <EmptyDataTemplate>
                                        <asp:Label ID="lbEmpty" runat="server" Text="資料庫目前無資料！"></asp:Label>
                                    </EmptyDataTemplate>
                                </asp:GridView>
                            </div>
                        </div>
                    </div>
 

					<div class="form-group text-center">
						<asp:Button ID="btnSubmit" runat="server" Text="送出" CssClass="btn btn-success" 
                            onclick="btnSubmit_Click"  />
						<asp:Button ID="btnBack" runat="server" CssClass="cancel btn btn-grey" 
                            Text="離開" onclick="btnBack_Click"  />
					</div>
				</div>
			</div>
		</div>
	</div>

    <script language ="javascript" type="text/javascript">
        $(function () {
            $('#<%=txtPkgCode.ClientID %>').change(function () {
                var CODE = $(this).val();
                $.ajax({
                    type: 'post',
                    url: "PkgAddEdit.aspx/CheckPkgCode",
                    data: "{ 'CODE':'" + CODE + "'}",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                            $('#<%=lbCheckCode.ClientID %>').text(data.d);
                    },
                    error: function () { alert('ajax failed'); }
                });
            });
        });
    </script>

    <script type = "text/javascript">
        function number_only(evt) {
            if (evt.charCode > 31 && (evt.charCode < 48 || evt.charCode > 57)) {
                //                alert("Allow Only Numbers");
                return false;
            }
        }
    </script>

</asp:Content>
