<%@ Page Title="套餐維護" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="PkgIndexEdit.aspx.cs" Inherits="HMCSys.PkgIndexEdit" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
<asp:HiddenField ID="hfCmd" runat="server" />
    <div class="row">
		<div class="col-sm-12">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h3 class="panel-title">
                        <asp:Label ID="Label1" runat="server" Text="套餐"></asp:Label></h3>
				</div>
				<div class="panel-body">
					<div class="form-group text-center">
						<span style="color: #FF5050">
							</span>
					</div>
					<div class="form-group">
						<span class="col-sm-2 control-label" style="color: #FF5050">*型態</span>
						<div class="col-sm-10">
                            <asp:RadioButtonList ID="type_list" runat="server" 
                                RepeatDirection="Horizontal" Enabled="False">
                                <asp:ListItem class="radio-inline" Value="0">類別</asp:ListItem>
                                <asp:ListItem class="radio-inline" Value="1">套餐</asp:ListItem>
                            </asp:RadioButtonList>
						</div>
					</div>
					<div class="form-group">
						<span class="col-sm-2 control-label" style="color: #FF5050">*名稱</span>
						<div class="col-sm-10">
							<asp:TextBox ID="txtName" runat="server" CssClass="form-control"></asp:TextBox>
						</div>
					</div>
                    <div id="pkg_panel" runat="server" clientidmode="Static">
                        <asp:Panel ID="Panel1" runat="server">
					        <div class="form-group text-center">
					        	<span class="col-sm-2 control-label" style="color: #FF5050">*套餐代碼</span>
					        	<div class="col-sm-10">
					        		<asp:TextBox ID="txtPkgCode" runat="server" CssClass="form-control"></asp:TextBox>
					        	</div>
					        </div>

                            <div class="table-responsive">
                                <asp:GridView ID="GridView1" runat="server" CssClass="table table-bordered" DataKeyNames="ItemCode" AutoGenerateColumns="false" AutoGenerateDeleteButton="False">
                                    <Columns>                                                                      
                                        <asp:BoundField HeaderText="細項代碼" DataField="ItemCode" />
                                        <asp:BoundField HeaderText="細項名稱" DataField="Memo" />
							            <asp:TemplateField HeaderText="刪除">
							            	<ItemTemplate>
                                                <asp:CheckBox ID="Ckb_Del" runat="server" />
							            	</ItemTemplate>
							            	<ItemStyle Width="60px" HorizontalAlign="Center" />
							            </asp:TemplateField>
                                    </Columns>
                                    <EmptyDataTemplate>
					        		    <asp:Label ID="lbEmpty" runat="server" Text="資料庫目前無資料！"></asp:Label>
					        	    </EmptyDataTemplate>
                                </asp:GridView>
                            </div>
                            <div class="container">
                                <table  class="table table-condensed">
                                    <tr>
                                        <td style="width: 100px">
                                            <br />
                                            <asp:Button ID="btnAdd" runat="server" Text="新增細項" CssClass="btn btn-success" 
                                                onclick="btnAdd_Click" />
                                        </td>
                                        <td style="width: 150px">
                                            細項代碼:<br />
                                            <asp:TextBox ID="txtItemCode" runat="server" CssClass="form-control"></asp:TextBox>
                                        </td>
                                        <td style="width: 150px">
                                            <br />
                                            <asp:TextBox ID="txtItemName" runat="server" CssClass="form-control" 
                                                Enabled="False" Visible="False"></asp:TextBox>
                                        </td>                                    
                                    </tr>
                                </table>
                            </div>

                        </asp:Panel>
                    </div>


					<div class="form-group text-center">
						<asp:Button ID="btnSubmit" runat="server" Text="送出" CssClass="btn btn-success" 
                            onclick="btnSubmit_Click"  />
						<asp:Button ID="btnBack" runat="server" CssClass="cancel btn btn-grey" 
                            Text="離開" onclick="btnBack_Click"  />
					</div>
				</div>
			</div>
		</div>
	</div>

    <script type="text/javascript">
        $(function () {
            $("[id*=type_list]").change(function () {
                var checked_radio = $("[id*=type_list] input:checked");
                var value = checked_radio.val();
                var text = checked_radio.closest("td").find("label").html();
                //                alert("Text: " + text + " Value: " + value);

                if (value == "1") {
                    $("#pkg_panel").css("visibility", "visible");
                }
                else {
                    $("#pkg_panel").css("visibility", "hidden");
                }
                return false;
            });
        });
    </script>
</asp:Content>
